[package]
name = "gc-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gc-cli"
path = "src/main.rs"

[dependencies]
gc= {path = "../gc"}
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]